version: "3"
services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRESS_DB: db
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: app
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
    - .:/usr/src/app
    - /home/app/node_modules


